package learning;

public class SyncronizationHelper {
	
	synchronized static public void general(String threadCode) {
		
		for(int i = 1; i<10;i++) {
			try {
				Thread.sleep(10);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			if(i<=5) {
				System.out.print("[");
			}else {
				System.out.print("]");
			}
		}
		System.out.println("generated by thread: " + threadCode);
		
		
	}
}
